import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import profilepic from "../public/profile.JPG";
import Image from "next/image";

import Card from "../components/Card";

export default function Home() {
  const frameworkUsed = ["Flask", "NodeJS", "React", "React Native"];
  const langUsed = ["Python", "JavaScript", "C#"];
  const devOpsUsed = ["Docker", "PostgreSQL", "MySQL", "MSSQL"];

  const projectList = [
    {
      title: "Triptify",
      description:
        "Triptify is a Fleet Management System which integrates web, mobile and map technology that tracks, dispatch and manage vehicles such as buses through a mobile app.",
      technologies: [
        "React",
        "NodeJS",
        "Flask",
        "React Native",
        "Redis",
        "MySQL",
        "PostgreSQL",
        "Map Box",
        "Docker",
        "Socket.IO",
        "SQLAlchemy",
        "Objection.js",
        "Material UI",
      ],
    },
    {
      title: "Forge",
      description:
        "Forge is a Barangay Management System which is a web-based application that automates\
         and simplify the processes of local government units in the Philippines.\
       Allows users to easily generate printable ID cards and other government documents.",
      technologies: [
        "React",
        "JavaScript",
        "Flask",
        "Python",
        "Material UI",
        "SQLAlchemy",
      ],
    },
    {
      title: "IPEPS",
      description:
        "Iloilo Provincial Employment Portal Services (IPEPS) with Data Analytics a \
        research project grant from Philippine Council for Industry, Energy and Emerging \
        Technology Research and Development (PCIEERD) which incorporates data analytics \
        to forecast real-time data and include relevant features such as recommending jobs \
        to a jobseeker with their profile.",
      technologies: [
        "React",
        "JavaScript",
        "Flask",
        "Python",
        "CoreUI",
        "SQLAlchemy",
      ],
    },
    {
      title: "Taxi Tracker Mobile App",
      description:
        "A taxi tracker mobile application using React Native which users can track their \
        location when riding a taxi. This will calculate the distance traveled based on the\
        user movement using the Haversine formula. This will also record the travel time,\
        cost, and traveled location of the user.",
      technologies: ["React Native", "JavaScript", "Expo"],
    },
    {
      title: "RotherfordTech",
      description:
        "My other portfolio build with React and Flask. https://rotherfordtech.onrender.com",
      technologies: ["React", "JavaScript", "Flask", "Python"],
    },
  ];

  return (
    <div>
      <Head>
        <title>Rotherford Marmibe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 bg-slate-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between text-white">
            <h1 className="font-roboto_italic text-xl">rotherfordm.</h1>
            <ul className="flex items-center">
              <li>
                <a
                  className="bg-gradient-to-r from-teal-500 text- to-green-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://rotherfordtech.s3.us-east-2.amazonaws.com/rotherfordtech/documents/github-pages/resume.pdf"
                  target="_blank"
                  rel="noopener"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 font-medium text-green-400 md:text-6xl">
              Rotherford Marmibe
            </h2>
            <h3 className="text-2xl py-2 text-white md:text-3xl">
              Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-200 max-w-xl mx-auto md:text-xl">
              Full-Stack Web Developer, Mobile Developer, lifelong learner, and
              passionate about innovation and technology.
            </p>
            <div className="mx-auto bg-gradient-to-b from-green-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={profilepic} layout="fill" objectFit="cover" />
            </div>
          </div>
          <div className="text-center p-10 py-10">
            <p className="text-md px-5 leading-8 text-gray-200 max-w-xl mx-auto md:text-xl">
              My other portfolio
            </p>
            <p className="text-md px-5 leading-8 text-gray-200 max-w-xl mx-auto md:text-xl">
              <a
                href="https://rotherfordtech.onrender.com"
                target="_blank"
                rel="noopener"
                className="underline"
              >
                rotherfordtech
              </a>
            </p>
            <p className="text-md px-5 py-5 leading-8 mx-auto">
              <a
                className="bg-gradient-to-r from-teal-500 text- to-green-500 text-white px-4 py-2 border-none rounded-md"
                href="https://rotherfordtech.s3.us-east-2.amazonaws.com/rotherfordtech/documents/github-pages/resume.pdf"
                target="_blank"
                rel="noopener"
              >
                Resume
              </a>
            </p>
          </div>
        </section>
        <section className="container mx-auto py-10">
          <div>
            <h3 className="text-3xl py-1 text-white text-center">
              Technologies
            </h3>
            <p className="font-roboto_light text-md text-white mt-3 text-center">
              {frameworkUsed.map((i, index) => {
                if (index === frameworkUsed.length - 1) {
                  return <span key={index}>{i}</span>;
                } else {
                  return <span key={index}>{i} • </span>;
                }
              })}
            </p>
            <p className="font-roboto_light text-md text-white mt-3 text-center">
              {langUsed.map((i, index) => {
                if (index === langUsed.length - 1) {
                  return <span key={index}>{i}</span>;
                } else {
                  return <span key={index}>{i} • </span>;
                }
              })}
            </p>
            <p className="font-roboto_light text-md text-white mt-3 text-center">
              {devOpsUsed.map((i, index) => {
                if (index === devOpsUsed.length - 1) {
                  return <span key={index}>{i}</span>;
                } else {
                  return <span key={index}>{i} • </span>;
                }
              })}
            </p>
          </div>
        </section>
        <section className="container mx-auto py-10">
          <h3 className="text-3xl py-1 text-white ">Projects</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2">
            {projectList.map((i) => {
              return (
                <Card
                  title={i.title}
                  description={i.description}
                  technologies={i.technologies}
                />
              );
            })}
          </div>
        </section>
      </main>
    </div>
  );
}
